# DO NOT EDIT THIS FILE
#
# Please edit /boot/env.txt to set supported parameters
#

setenv scriptaddr "0x01000000"
setenv kernel_addr_r "0x01300000"
setenv fdt_addr_r "0x05000000"
setenv consoleargs "console=ttyAML0,115200"

# default values
setenv rootdev "/dev/mmcblk1p1"
setenv verbosity "1"
setenv rootfstype "ext4"

if test -e ${devtype} ${devnum} env.txt; then
	echo "Found env.txt at ${devtype} ${devnum}"

	fatload ${devtype} ${devnum} ${scriptaddr} env.txt
	env import -t ${scriptaddr} ${filesize}

	echo "Current fdtfile after env: ${fdtfile}"

	setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} ${consoleargs} consoleblank=0 coherent_pool=2M loglevel=${verbosity} ubootpart=${partuuid} usb-storage.quirks=${usbstoragequirks} ${extraargs}"

	echo "Mainline bootargs: ${bootargs}"

	fatload ${devtype} ${devnum} ${kernel_addr_r} ${prefix}Image
	fatload ${devtype} ${devnum} ${fdt_addr_r} ${prefix}${fdtfile}
	fdt addr ${fdt_addr_r}
	fdt resize 65536

	booti ${kernel_addr_r} - ${fdt_addr_r}
fi

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
